### ISSUE TITLE
Error with 'authoryear' format

### ISSUE THREAD

**Issue by jvcasill** [mwmclean/RefManageR#12]
When I try to print by bib entry I get the following error:

    Error in if (grepl("[.?!]$", tl, useBytes = TRUE)) { : argument is of length zero

This is the command I am using to create the entry:

    print(bib[key = "myKey"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authoryear"))

Any idea what might be happening?

**Comment by mwmclean** [comment]
Not without you providing a minimal example (i.e. a minimal .bib file) that produces the problem.  It should be enough to provide the output of

```
toBiblatex(bib[key = "myKey"])
```

**Comment by jvcasill** [comment]
Thank you for your reply. I came to the same conclusion. For the sake of completeness, the following information should give you a minimal working example:

    @Article{myKey,
      author = {My Author and My Friend},
      title = {Production and perception of the English /æ/-/ɑ/ contrast},
      year = {2016},
      volume = {32},
      number = {2},
      pages = {171-195},
      journal = {My Journal},
    }

    toBiblatex(bib[key = "myKey"])
    print(bib[key = "myKey"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authoryear"))

The ```toBiblatex()``` works fine. The ```print()``` function gives me issues, and only when the bib.style is "authoryear".
