### ISSUE TITLE
Issue when author list on GS includes ...

### ISSUE THREAD

**Issue by markjohnsonubc** [mwmclean/RefManageR#13]
RefManageR seems to have trouble ingesting references from GS profile that include "..." on the author list on the GS main page. When the GS scholar profile page shows an author list truncated to conclude with "...", ReadGS() throws an error, stating:
"Incomplete author information for entry "Physiological responses to extreme hydrological events in the Pantanal wetland: heterogeneity of a plant community containing super‐dominant species" it will NOT be added"

Trying to paste a screenshot of what I mean from the GS profile page that lists this reference title. 
![image](https://cloud.githubusercontent.com/assets/10761097/14934001/d724b80e-0e56-11e6-853b-2298a7d88c21.png)

This package seems incredibly helpful, but this function currently throws an error. When the same profile is ingested by get_publications() on R package "scholar", it shows the author list as "HJ Dalmagro, MJ Lathuillière, GL Vourlitis, RC Campos, OB Pinto, ..." - not idea either since the GS entry for the paper includes the full author list (i.e., not truncated as "...")

Seems that "..." functions as "et al." on GS profile pages, while reference pages include full author lists, so must be in the GS data somewhere

**Comment by mwmclean** [comment]
This is working as documented; see the details and examples in the help file ```?ReadGS```.  If you want the entries to be added to the BibEntry object even though there is incomplete info, then before calling ```ReadGS``` execute the following
```
BibOptions(check.entries = FALSE)
```
or
```
BibOptions(check.entries = "warn")
```

**Comment by markjohnsonubc** [comment]
Great - and thanks for the reply. I hadn't clued in to putting that first, though it is in the example. Perhaps including an example in the help file with it included in the function call would be helpful. Maybe something like:
ReadGS(scholar.id = x, sort.by.date = TRUE, check.entries = FALSE)
