### ISSUE TITLE
PrintBibliography() produces \Sexpr in .rmd file

### ISSUE THREAD

**Issue by alexandergerber** [mwmclean/RefManageR#15]
I have an issue with compiling my .rmd file. `PrintBibliography()` produces, if there is a doi, sweave instead of rmarkdown syntax. In my example it looks like that:  `\Sexpr[results=rd,stage=build]{tools:::Rd_expr_doi("10.1177/0011000008316034")}`
Is there a way to prevent this from happening?

**Comment by mwmclean** [comment]
Can you please provide me with a minimal .rmd file that reproduces the problem?

**Comment by alexandergerber** [comment]
I am not able to compile this in RStudio.     
    ---
    output: pdf_document
    ---

    ```{r}
    library(RefManageR)
     bib <- bibentry(bibtype = "article", key = "Algan.2010", title = "Inherited Trust and Growth",
    journal = "American Economic Review", year = 2010, author = "Algan, Yann and Cahuc, Pierre", doi = "10.1257/aer.100.5.2060")
    ```
    `r Cite(bib, "Algan.2010")`

    ```{r, results='asis'}
     PrintBibliography(bib, .opts = list( bib.style = "JSS", style = "citation"))
    ```

The error message I get is: 

> ! Undefined control sequence.
> l.143 \Sexpr

**Comment by mwmclean** [comment]
You are calling the function `utils::bibentry` instead of the function `RefManageR::BibEntry`.  If you use the actual function from `RefManageR`, the problem will go away.
