### ISSUE TITLE
ReadGS breaks when GS entry points to multiple scholar articles?

### ISSUE THREAD

**Issue by markjohnsonubc** [mwmclean/RefManageR#17]
Below is a bit of code that works for the first 6 entries, but then breaks on the 7th. Then another scholar ID that works for first 8 but not on 9th. 

Could be encoding issue? Found non-standard characters in Title and Publication fields when exporting the offending entries as csv files (uploaded in zip attachment). However, since the order of the entries in the BibEntry object seems different from the order on GS page when sorted by year, I'm not sure what is causing the error. 

Error statement:

Error in tolower(regmatches(ti, m)) : 
  translating strings with "bytes" encoding is not allowed

### 
BibOptions(check.entries = FALSE)
ReadGS(scholar.id = "KfQwll4AAAAJ", limit = 6, sort.by.date = TRUE) # first 6 OK
ReadGS(scholar.id = "KfQwll4AAAAJ", limit = 7, sort.by.date = TRUE) # 7th causes error

ReadGS(scholar.id = "KfQwll4AAAAJ", limit = 8, sort.by.date = TRUE) # first 8 OK
ReadGS(scholar.id = "KfQwll4AAAAJ", limit = 9, sort.by.date = TRUE) # 9th causes error
###

**Comment by markjohnsonubc** [comment]
[CitationsFromGS.zip](https://github.com/mwmclean/RefManageR/files/362079/CitationsFromGS.zip)

**Comment by mwmclean** [comment]
Thanks for bring this to my attention and sorry for the slow reply.  The error was occurring in my function for creating the entry keys.  The function was not properly dealing with the case when a word from the title containing a non-ascii character was chosen for the key.  This should be corrected now.
