### ISSUE TITLE
Use rcrossref to avoid deprecated crossref API

### ISSUE THREAD

**Issue by cboettig** [mwmclean/RefManageR#18]
Looks like RefManageR is using the older CrossRef API that is apparently slated to be deprecated.  Perhaps you would consider using the functions from [rcrossref](https://github.com/ropensci/rcrossref) as an ready way to make calls against the new API?

**Comment by mwmclean** [comment]
Thanks for pointing this out.  I will investigate how much trouble it is to update the functions I've already implemented before having a look at `rcrossref`.  I already have too many dependencies as it is.  At the very least, I'll mention your package in the See Also section of my documentation.

**Comment by raymond9620** [comment]
Please take me off this list
