### ISSUE TITLE
URI Too Large

### ISSUE THREAD

**Issue by mevers** [mwmclean/RefManageR#19]
Hi @mwmclean 

I am trying to use RefManageR to pull bibliography data from PubMed using the function `ReadPubMed(...)`. For a lot of search strings the function throws errors `Error: Request-URI Too Large`.

Here is a minimal example to reproduce such an error:
```{R}
getPubs <- function(ss, retmax = 1000, mindate = 2000, maxdate = 2016) {
    # Load library to allow communication with PubMed
    library(RefManageR);
    # Search for author in PubMed
    lst <- lapply(ss, function(x)
                  ReadPubMed(x,
                             database = "PubMed",
                             field = "author",
                             retmax = retmax,
                             mindate = mindate,
                             maxdate = maxdate));
    names(lst) <- ss;
    return(lst);
}
getPubs("Martin Nicholas")
```
This produces
```{R}
Error: Request-URI Too Large
```
Do you have any advice on how to avoid this? The issue for me is the combination of `lapply` and `ReadPubMed` which means that the information on 99 authors can be lost, if the 100th author query string throws above error.

Best,
Maurits

**Comment by mwmclean** [comment]
One possibility is to reduce `retmax` in the call to `ReadPubMed` and make multiple calls to `ReadPubMed` using different values of the `retstart` argument until you reach the `retmax` value passed to your `getPubs`.

**Comment by mevers** [comment]
Thanks for the suggestion.
Following your advice, one could do
```{R}
getPubs <- function(ss, retmax = 1000, mindate = 2000, maxdate = 2016) {
    # Load library to allow communication with PubMed
    library(RefManageR);
    # Search for author in PubMed
    lst <- lapply(ss, function(x) {
        chunks <- split(seq(retmax), ceiling(seq(retmax)/100));
        sapply(chunks, function(y)
               ReadPubMed(x,
                          database = "PubMed",
                          field = "author",
                          retmax = 100,
                          retstart = y[1],
                          mindate = mindate,
                          maxdate = maxdate))
        });
    names(lst) <- ss;
    return(lst);
}
```
This throws some warnings if there are in fact less than 1000 entries, in which case the last `retstart` offset values refer to non-existing entries. It's ugly, but seems to work.

I don't understand why the error shows up in the first place. If I use the command line NCBI Entrez utilities there is no issue with above example search string.

Best,
Maurits

**Comment by mwmclean** [comment]
Can't say without knowing the command you're using.  Will come down to differences between it and `RCurl::getForm`.  Note that the "warnings" are just messages that there were no results and not actual R warnings.  Here's a function I wrote with a couple tweaks to yours that you may or may not find useful:
```
getPubs <- function(ss, retmax = 1000, mindate = 2000,
			 maxdate = 2016, chunk.size = 100) {
    # Load library to allow communication with PubMed
    require(RefManageR)
    # Search for author in PubMed
    chunks <- seq.int(1, retmax, by = chunk.size)
    do.call(c, lapply(ss, function(x) {
	   bib <- vector("list", length(chunks))
	   for (i in seq_along(chunks)){
               bib[[i]] <- ReadPubMed(x,
                          database = "PubMed",
                          field = "author",
                          retmax = 100,
                          retstart = chunks[i],
                          mindate = mindate,
                          maxdate = maxdate)	      		 
	       if (!length(bib[[i]]))
			  break
	   }
           do.call(c, bib[!sapply(bib, is.null)])
    }))
}
```
You will get a single `BibEntry` object instead of a list of lists of `BibEntry` objects.  Also, slightly more efficient because the loop stops right after the first failure to retrieve any entries.

**Comment by mevers** [comment]
Much neater! Thanks @mwmclean.

PS. Just for the record, here is the command line esearch command
```{bash}
esearch -db pubmed -mindate 2000 -maxdate 2016 -query "Martin Nicholas" | efetch -format medline
```
As far as I can see, there is no `retmax` option for `esearch`.

Feel free to delete this post as it's not relevant to RefManageR.

**Comment by mwmclean** [comment]
The difference was because my code was using GET instead of POST (`RCurl::getForm` instead of `RCurl::postForm`).  Better to POST when requesting so many records.  I switched to postForm in 2a08e809186bd5f5b5407e3f4383bc73e2f44c01.

**Comment by mevers** [comment]
Thanks and great work @mwmclean.
