### ISSUE TITLE
Hyperlink title of article

### ISSUE THREAD

**Issue by jblumenau** [mwmclean/RefManageR#21]
Hi, 

Imagine that I have a paper like this:

```
@article{author2016interesting,
    Author = {An Author},
    Journal = {Very Good Journal},
    Title = {Interesting Paper},
    Url = {http://www.verygoodjournal.com/interestingpaper},
    Year = {2016}}

```

Using `print.Bibentry` with `style = "markdown"` gives me:

```
Author, A. (2016). “Interesting Paper”. In: _Very Good Journal_. URL:
[http://www.verygoodjournal.com/interestingpaper](http://www.verygoodjournal.com/interestingpaper).
```

But I'd really like to have:

```
Author, A. (2016). [“Interesting Paper”](http://www.verygoodjournal.com/interestingpaper). In: _Very Good Journal_. 
```

That is, rather than displaying the url directly, I'd like to embed it as a hyperlink for the title of the paper. Is that possible at all?

Many thanks, and great package!

Jack

**Comment by mwmclean** [comment]
This should be possible by defining a custom `bibstyle`.  See `?tools::bibstyle` and the functions in the environment returned by `RefManageR:::MakeBibLaTeX`.  For example

```
env <- RefManageR:::MakeBibLaTeX()
env$formatArticle
env$fmtJTitle
env$fmtURL
```

A custom `bibstyle` with different definitions for `fmtJTitle` and `fmtURL` should achieve what you want.
