### ISSUE TITLE
ReadPubMed returns 20 citations by default 

### ISSUE THREAD

**Issue by dalewsteele** [mwmclean/RefManageR#23]
ReadPubMed now retrieves only 20 citations with default parameters.  This appears to be a change in behavior from previous.  Documentation of this behavior would be helpful.  Should a higher 'retmax' be default? 

```
library(RefManageR)
chs <- ReadPubMed("Schmid CH[au]", database="PubMed")
length(chs)
```

**Comment by mwmclean** [comment]
Thanks for pointing this out.  I decided to just mention that the default is 20 in the documentation, and not specify a default for retmax in the function arguments.
