### ISSUE TITLE
Bibliography format

### ISSUE THREAD

**Issue by sammo3182** [mwmclean/RefManageR#26]
@mwmclean, thank you for building such useful package! I have three quick questions about using it (V 0.13.3) to print out the bibliography. First, I found there's always an "In" before the journal name for article bibs as the following example, no matter what style of bib I choose. Is there a way to take it out?

```markdown
 Frederick Solt, Yue Hu, Kevan Hudson, et al. “Economic Inequality and Belief in Meritocracy in the
United States”. In: Research & Politics 3.4 (2016), pp. 1-7. DOI: 10.1177/2053168016672101. eprint: http:
//rap.sagepub.com/content/3/4/2053168016672101.full.pdf. <URL: http://rap.sagepub.com/content/
3/4/2053168016672101>.
```

Second, you can see in the above example, the output includes DOI and eprint and embeds the URL in a `<>`. Is there anyway I can not showing the eprint or any element in the bib but not change the original bib file? Also, is there a way to take the `<>` off.

Finally, when I use the default `markdown` style for output, the journal titles are not Italic. Is there's a way to fix that?

All of my questions may relate to the style setting of bib output. I'm a beginner of .bib. So forgive me if these questions are too simple, and I will appreciate if you could offer me some help to solve them. Thank you.

**Comment by mwmclean** [comment]
This is all possible by defining a custom bibstyle.  Please see #21 and let me know if you still have questions.

**Comment by sammo3182** [comment]
@mwmclean, thank you for the reply. The information does help. I tried to create a new style as following:
```r
custom <- RefManageR:::MakeBibLaTeX()
custom$fmtJournal <- function(s){
                                if (length(s$journaltitle)) {
                                    res <- emph(cleanupLatex(s$journaltitle))
                                    if (length(s$journalsubtitle)) 
                                        res <- paste(addPeriod(res), emph(cleanupLatex(s$journalsubtitle)))
                                    return(res)
                                }
                                else if (!is.null(s$journal)) {
                                    emph(cleanupLatex(s$journal))
                                }
                            }
```

But is that all I need to do? I tried to call this style in `BibOptions(bib.style = custom)`, but it doesn't work. Could I ask for some more information about how to customize `bibstyle`? Thank you.

**Comment by mwmclean** [comment]
Did you call `tools::bib.style` to register the new style?  There is an added complication in your example due to the scope of the formatting functions `emph`, `cleanupLatex`, etc. when redefining functions like `fmtJournal`.  One way to handle this is using the function `with`.  The following example works on my machine.
```
library(RefManageR)
custom <- RefManageR:::MakeBibLaTeX()
with(custom,
custom$fmtJournal <- function(s){
                                if (length(s$journaltitle)) {
                                    res <- emph(cleanupLatex(s$journaltitle))
                                    if (length(s$journalsubtitle)) 
                                        res <- paste(addPeriod(res), emph(cleanupLatex(s$journalsubtitle)))
                                    return(res)
                                }
                                else if (!is.null(s$journal)) {
                                    emph(cleanupLatex(s$journal))
                                }
})

tools::bibstyle("custom", custom)
BibOptions(bib.style = "custom")
bib <-      BibEntry(bibtype = "Article", key = "mclean2014", title = "An Article Title",
       author = " McLean, Mathew W. and Wand, Matt P.", journaltitle = "The Journal Title",
       date = "2014-02-06", pubstate = "forthcoming")
bib

## M. W.  McLean and M. P. Wand. “An Article Title”. _The Journal Title_
## (Feb. 06, 2014). Forthcoming.
```
