### ISSUE TITLE
Error generated by citation without AuthorList

### ISSUE THREAD

**Issue by dalewsteele** [mwmclean/RefManageR#3]
I now have many fewer PMIDs that cannot be parsed by GetPubMedByID.  However, after the recent code updates, a citation with no AuthorList generates the following error.

> GetPubMedByID("7936917")

Error in if (complete.AuthorList == "N") warning(paste0("Incomplete list of authors returned by PubMed for ID: ",  : 
  argument is of length zero

**Comment by mwmclean** [comment]
What other PMIDs cannot you now not retrieve that you could before?

**Comment by dalewsteele** [comment]
Very cool! After #3 fixed, GetPubMedByID now retrieves (with appropriate warnings) all of the PMIDs in my current project.
