### ISSUE TITLE
Problem with `\&` in rmarkdown output

### ISSUE THREAD

**Issue by sammo3182** [mwmclean/RefManageR#30]
I'm incorporating `RefManageR` outputs in a Rmarkdown file. The bib info is like this in my `.bib` file:
```
@InBook{Przeworski1970,
  pages     = {31--46},
  title     = {Research Design},
  publisher = {Joh Wiley \& Sons},
  year      = {1970},
  author    = {Przeworski, Adam and Teune, Henry},
  address   = {New York},
  booktitle = {The Logic of Comparative Social Inquiry},
}
```
The `\` before `&` in `publisher` was added in purpose for latex compilers to read accurately. However, `RefManageR` automatically recorganized that as a character and added a `\bsl{}`:

```
Adam Przeworski and Henry Teune.
``Research Design''. In: \emph{The Logic of Comparative Social Inquiry}. New York: Joh Wiley \bsl{}\& Sons, 1970, pp. 31--46.
```
It cauesed my file failed to be compiled by Rmarkdown. Is there anyway I can avoid this? 

Thanks,

**Comment by mwmclean** [comment]
I am unable to reproduce this.  Can you please provide me with a reproducible example and your `sessionInfo()`?

**Comment by sammo3182** [comment]
My `sessionInfo`:

``` r
sessionInfo()
#> R Under development (unstable) (2017-06-02 r72758)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 15063)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.5.0       backports_1.1.0      magrittr_1.5        
#>  [4] rprojroot_1.2        formatR_1.5          tools_3.5.0         
#>  [7] htmltools_0.3.6      yaml_2.1.14          Rcpp_0.12.11        
#> [10] stringi_1.1.5        rmarkdown_1.6.0.9000 knitr_1.16          
#> [13] stringr_1.2.0        digest_0.6.12        evaluate_0.10
```
Here's a minimum sample:

``` r
library(RefManageR)
bib <- ReadBib("reading.bib", check = FALSE)
bib
#> Adam Przeworski and Henry Teune.
#> ``Research Design''.
#> In: 
#> \emph{The Logic of Comparative Social Inquiry}.
#> New York: Joh Wiley \bsl{}\& Sons, 1970, pp. 31--46.
```
Please know that the input file has to be a bib file rather than directly input in R. Here's the content of my `reading.bib`:

```bib
@InBook{Przeworski1970,
  pages     = {31--46},
  title     = {Research Design},
  publisher = {Joh Wiley \& Sons},
  year      = {1970},
  author    = {Przeworski, Adam and Teune, Henry},
  address   = {New York},
  booktitle = {The Logic of Comparative Social Inquiry},
  timestamp = {2017-06-20},
}
```

Thank you.

**Comment by mwmclean** [comment]
I am able to reproduce this only when I add `BibOptions(style = "latex")` to your example.  The `\bsl{}` is added by `tools::Rd2latex`.   We can reproduce this in base R using
```
print(bibentry(bibtype = "misc", key = "key", title = "\\&"), style = "latex")
## (????).
## ``\bsl{}\&.''
```

Could @dmurdoch possibly offer advice?  I attempted to add `\newcommand{\&}{&}` to `man/macros/macros.Rd` and pass that to `parse_Rd`, but that is not working.

**Comment by dmurdoch** [comment]
Rd2latex assumes the input is in Rd format, and since \& isn't an Rd macro, it assumes the user wanted an explicitly displayed backslash.  The code that reads the .bib file containing this should deal with any macros that don't correspond to Rd macros and not pass them to Rd2latex.

You can probably define \& as an Rd macro and have it handled that way, but handling those isn't straightforward.   Take a look at Rd handling in the tools package to see the steps.
