### ISSUE TITLE
Bug in ReadBib

### ISSUE THREAD

**Issue by relund** [mwmclean/RefManageR#32]
If I have the following BibTeX file:

@TechReport{Nielsen17,
  author       = {L Nielsen},
  title        = {A title},
  institution  = {DTU},
  year         = {2017},
  type         = {resreport}
}

and run

RefManageR::ReadBib("tmp.bib")

Then I get 

Error in formatReport(paper, typ) : unused argument (typ)

Is this a bug?

**Comment by mwmclean** [comment]
I cannot reproduce this.  I get
```
## L. Nielsen. _A title_. Research rep. DTU, 2017. <URL:
## http://www.optimization-online.org/DB_HTML/2017/04/5940.html>.
```
Are you using the latest version of the package?  Is there anything else in tmp.bib?  Have you changed any formatting options using `RefManageR::BibOptions`?

**Comment by relund** [comment]
Installing the dev version seems to fix it. Sorry should have checked this first.
