### ISSUE TITLE
DOIs with links

### ISSUE THREAD

**Issue by relund** [mwmclean/RefManageR#33]
Given file:

@ARTICLE{Gadegaard16b,
author = {S.L. Gadegaard and A Klose and L.R. Nielsen},
title = {A bi-objective approach to discrete cost-bottleneck location problems},
year = {2016},
journal = {Annals of Operations Research},
pages = {1-23},
doi = {10.1007/s10479-016-2360-8}
}

and running 

RefManageR::ReadBib("tmp.bib")

gives 

```
[1] S. Gadegaard, A. Klose and L. Nielsen. “A bi-objective approach to discrete cost-bottleneck location
problems”. In: _Annals of Operations Research_ (2016), pp. 1-23. DOI: 10.1007/s10479-016-2360-8. 
``` 

It could be nice if it could link the DOI, i.e. output 

```
[1] S. Gadegaard, A. Klose and L. Nielsen. “A bi-objective approach to discrete cost-bottleneck location
problems”. In: _Annals of Operations Research_ (2016), pp. 1-23. DOI: [10.1007/s10479-016-2360-8](http://dx.doi.org/10.1007/s10479-016-2360-8).
```

Is that possible (or maybe a quick hack)?

**Comment by mwmclean** [comment]
Yes, this is already implemented.  The default printing style, is simply text so the link is not produced.  For example
```
library(RefManageR)
BibOptions(style = "markdown")
ReadBib("tmp.bib")
## S. Gadegaard, A. Klose and L. Nielsen. “A bi-objective approach to
## discrete cost-bottleneck location problems”. In: _Annals of Operations
## Research_ (2016), pp. 1-23. DOI:
## [10.1007/s10479-016-2360-8](http://dx.doi.org/10.1007/s10479-016-2360-8).
```
Please see `?RefManageR::BibOptions` and the vignette `vignette("manual", package = "RefManageR")`

**Comment by relund** [comment]
Thanks.
