### ISSUE TITLE
Pandoc format citations in rmarkdown

### ISSUE THREAD

**Issue by dalewsteele** [mwmclean/RefManageR#5]
---
title: "Using Citations"
author: "Dale Steele"
date: "April 4, 2015"
output: word_document
bibliography: myCitations.bib
csl: jama.csl
---

I'd like to be able to more easily use Pandoc type citations.  For example, the inline citation created with paste0 works for a single citation.

```{r}
library(RefManageR)
dws <- ReadPubMed("Steele DW[au]", database="PubMed")
WriteBib(dws, file="myCitations.bib", biblatex=TRUE)
```

A single citation.`r paste0("[@", dws[author="Trikalinos"]$key, "]")`

**Comment by dalewsteele** [comment]
A little closer to what I had in mind to generate pandoc type citations.   Two rough functions to generate pandoc type citations utilizing wrappers for your cool RefManageR{SearchBib} function:

      citepd <- function (mylist, ...){
                 mycite <- sprintf('[@%s]', paste0(unlist(mylist$key), collapse = '; @'))
                 return(mycite)
                 }

Blah Blah Blah. `r citepd(dws[author="Santucci"])`

    citePMID <- function (bib, pmid, ...){
                        mycite <- sprintf('[@%s]', paste0(unlist(bib[eprint=pmid]$key), collapse = '; @'))
                     return(mycite)
                 }

blah blah blah. `r citePMID(dws, "25669699")`

**Comment by mwmclean** [comment]
This should be working now.  Some examples below.
```
library(RefManageR)
dws <- ReadPubMed("Steele DW[au]", database="PubMed")
Citet(dws, title = "Varicella", .opts = list(cite.style = "pandoc"))
## [1] "[@simon1995varicella]"

BibOptions(cite.style = "pandoc")
Citep(dws, eprint = c(9043537, 7802360))
## [1] "@wright1997evaluation; @simon1995varicella"
```
