### ISSUE TITLE
bib file imports but won't print

### ISSUE THREAD

**Issue by jvcasill** [mwmclean/RefManageR#6]
I use the following command to import my .bib file: 

    bib <- ReadBib("./data/publicationsCV.bib", check = "error")

I get the following error repeated multiple times:

    Ignoring entry 'XXXX' (line14) because:
	A bibentry of bibtype 'Conference' has to specify the field: editor

My bib entry does indeed have the 'Editor' field. In any case, when I set ```check = FALSE```, the file imports, but won't print (i.e. via ```print(bib)```... this gives me the same error. If I print using

    print(bib, .opts = list(check.entries = FALSE))

The R session freezes and I have to restart. Any idea what's going on?

**Comment by mwmclean** [comment]
Sounds like there are some characters in the editor field of that entry that the parser does not like.  Please paste the offending entry in a reply.

**Comment by jvcasill** [comment]
This is exactly what the issue was. Some of the entries have IPA characters and are rendered via the ```tipa``` package in latex. I removed the code for the characters and used the UTF-8 counterparts. I can now load the file without problems. Thank you.
