### ISSUE TITLE
Apparent loss of eprint ID when converting BibEntry to data frame 

### ISSUE THREAD

**Issue by dalewsteele** [mwmclean/RefManageR#8]
Hi - When converting from a BibEntry object created using GetPubMedByID() to a data frame using as.data.frame(), I appear to reproducibly lose two eprint IDs.  See rcode (and my results) using test file on dropbox and rcode below.  Thanks for any insights as to why this is happening.

    download.file("https://dl.dropboxusercontent.com/u/6728326/PubMedIDs.RData", "PubMedIDs.RData")
    load("PubMedIDs.RData")

    library(RefManageR)
    pmids_be <- GetPubMedByID(pmids)
    pmids_be[[336:338]]$eprint

Produces:
    $black1990randomised
    [1] "2196954"

    $valtonen2005year
    [1] "15837895"

    $roland2004topical
    [1] "14702493"

However,
    pmids_df <- as.data.frame(pmids_be)
    pmids_df$eprint[336:338]

Produces:
    > pmids_df$eprint[336:338]
    [1] "2196954" NA        NA

**Comment by mwmclean** [comment]
Thanks for the report.  This actually occurs because those two entries have the same key values as two other entries.  I will update RefManageR to require the keys in a BibEntry object to always be unique.
