### ISSUE TITLE
Is there a limit to the length of the list of authors

### ISSUE THREAD

**Issue by PietaSchofield** [mwmclean/RefManageR#9]
Is there a known limit to the number of authors. I have a 500 entry bibtex file that never returns (with madly whirring cpu fan) when trying to load with ReadBib if the following entry is include but loads fine with in a second or so if I delete the entry. If I delete most of the authors it also works

@article{Cunningham28102014,
author = {Cunningham, Fiona and Amode, M. Ridwan and Barrell, Daniel and Beal, Kathryn and Billis, Konstantinos and Brent, Simon and Carvalho-Silva, Denise and Clapham, Peter and Coates, Guy and Fitzgerald, Stephen and Gil, Laurent and Girón, Carlos García and Gordon, Leo and Hourlier, Thibaut and Hunt, Sarah E. and Janacek, Sophie H. and Johnson, Nathan and Juettemann, Thomas and Kähäri, Andreas K. and Keenan, Stephen and Martin, Fergal J. and Maurel, Thomas and McLaren, William and Murphy, Daniel N. and Nag, Rishi and Overduin, Bert and Parker, Anne and Patricio, Mateus and Perry, Emily and Pignatelli, Miguel and Riat, Harpreet Singh and Sheppard, Daniel and Taylor, Kieron and Thormann, Anja and Vullo, Alessandro and Wilder, Steven P. and Zadissa, Amonida and Aken, Bronwen L. and Birney, Ewan and Harrow, Jennifer and Kinsella, Rhoda and Muffato, Matthieu and Ruffier, Magali and Searle, Stephen M.J. and Spudich, Giulietta and Trevanion, Stephen J. and Yates, Andy and Zerbino, Daniel R. and Flicek, Paul}, 
title = {Ensembl 2015},
year = {2014}, 
journal = {Nucleic Acids Research} 
}

**Comment by mwmclean** [comment]
The issue is with the umlaut a in Kähäri.  Replacing Kähäri with K{\"a}h{\"a}ri in the entry works for me.

**Comment by PietaSchofield** [comment]
Hullo 

Thanks I thought I had tried that maybe I just missed one of them

Pieta
